name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Base
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: base-test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Test "demo" project in the tests/ folder
      # this should compile without any warnings or errors!
      - name: Test
        run: |
          docker run -v "$(pwd)"/tests/demo:/demo test bash -c "cd /demo && make"

      - name: Build MLIR
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.mlir
          build-args: |
            BASE_IMG=base-test
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # so I really need this?
      - name: Docker meta (Base)
        id: meta-base
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          # set latest tag for default branch
          tags: |
            type=raw,value=base
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build Base
        uses: docker/build-push-action@v5
        with:
          tags: ${{ steps.meta-base.outputs.tags }}
          labels: ${{ steps.meta-base.outputs.labels }}
          cache-from: type=gha

      - name: Docker meta (mlir)
        id: meta-mlir
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          # set latest tag for default branch
          tags: |
            type=raw,value=latest-mlir,enable={{is_default_branch}}

      - name: Build MLIR
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile.mlir
          build-args: |
            BASE_IMG=ghcr.io/${{ github.repository }}:base
          tags: ${{ steps.meta-mlir.outputs.tags }}
          labels: ${{ steps.meta-mlir.outputs.labels }}
          cache-from: type=gha
